/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autos;

 
import inventario.Imagen;
import inventario.Postgresql;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jefferson
 */
public class Autos extends javax.swing.JInternalFrame {
private Postgresql Pg = new Postgresql();
    String driver = "org.postgresql.Driver";
    String ruta = "jdbc:postgresql://localhost:5432/AutoCar";
    String user = "postgres";
    String password = "12345"; 
    DefaultTableModel modelo;
    DefaultListModel dml = new DefaultListModel();
     private DefaultListModel modListaImagen = new DefaultListModel();
     String rutaEdit="";
     String rutaGuardar="";
    /**
     * Creates new form Cliente
     */
    public Autos() throws ClassNotFoundException, SQLException {
        initComponents();
        cargarTodos();
        tr=new TableRowSorter<>(modelo);
    }
 
    TableRowSorter<TableModel> tr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        autoPlaca = new javax.swing.JTextField();
        autoModelo = new javax.swing.JTextField();
        autoMarca = new javax.swing.JTextField();
        autoChasis = new javax.swing.JTextField();
        autoMotor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        autoKilo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        autoCosto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        autoTransmision = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        autoAnio = new javax.swing.JComboBox<>();
        AutoImg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        autoEditBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        autoModeloEdit = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        autoMarcaEdit = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        autoChasisEdit = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        autoMotorEdit = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        autoKiloEdit = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        autoCostoEdit = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        autoTransmisionEdit = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        autoBotonEdit = new javax.swing.JButton();
        autoAnioEdit = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        AutoImgEdit = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cliTabla = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        filter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(50, 93, 127));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Agregar auto");

        autoPlaca.setName(""); // NOI18N
        autoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoPlacaActionPerformed(evt);
            }
        });

        autoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoModeloActionPerformed(evt);
            }
        });

        autoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMarcaActionPerformed(evt);
            }
        });

        autoChasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoChasisActionPerformed(evt);
            }
        });

        autoMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMotorActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Agregar");

        jLabel3.setText("Placa");

        jLabel6.setText("Modelo");

        jLabel7.setText("Marca");

        jLabel8.setText("Año");

        jLabel9.setText("Chasis");

        jLabel10.setText("Motor");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deny.png"))); // NOI18N
        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel18.setText("Kilometraje");

        autoKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoKiloActionPerformed(evt);
            }
        });

        jLabel19.setText("Costo");

        autoCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoCostoActionPerformed(evt);
            }
        });

        jLabel20.setText("Transmisión");

        autoTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automática" }));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addImagen.png"))); // NOI18N
        jButton9.setText("Cargar Imagen");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel21.setText("Imagen");

        autoAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2013", "2014", "2015", "2016", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 147, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(autoModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(autoMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoChasis, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoMotor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoKilo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoPlaca)
                                    .addComponent(autoCosto)
                                    .addComponent(autoAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9)
                                    .addComponent(autoTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(autoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoKilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(autoTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        AutoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AutoImg, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(AutoImg))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        autoEditBuscar.setText("Placa");
        autoEditBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoEditBuscarMouseClicked(evt);
            }
        });
        autoEditBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoEditBuscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Editar Auto");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Editar");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deny.png"))); // NOI18N
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        autoModeloEdit.setEnabled(false);
        autoModeloEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoModeloEditActionPerformed(evt);
            }
        });

        jLabel22.setText("Modelo");

        jLabel23.setText("Marca");

        autoMarcaEdit.setEnabled(false);
        autoMarcaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMarcaEditActionPerformed(evt);
            }
        });

        jLabel24.setText("Año");

        jLabel25.setText("Chasis");

        autoChasisEdit.setEnabled(false);
        autoChasisEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoChasisEditActionPerformed(evt);
            }
        });

        jLabel26.setText("Motor");

        autoMotorEdit.setEnabled(false);
        autoMotorEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMotorEditActionPerformed(evt);
            }
        });

        jLabel27.setText("Kilometraje");

        autoKiloEdit.setEnabled(false);
        autoKiloEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoKiloEditActionPerformed(evt);
            }
        });

        jLabel28.setText("Costo");

        autoCostoEdit.setEnabled(false);
        autoCostoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoCostoEditActionPerformed(evt);
            }
        });

        jLabel29.setText("Transmisión");

        autoTransmisionEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automática" }));
        autoTransmisionEdit.setEnabled(false);

        jLabel30.setText("Imagen");

        autoBotonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addImagen.png"))); // NOI18N
        autoBotonEdit.setText("Cargar Imagen");
        autoBotonEdit.setEnabled(false);
        autoBotonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoBotonEditActionPerformed(evt);
            }
        });

        autoAnioEdit.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autoKiloEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoCostoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoMotorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoChasisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoBotonEdit)
                                    .addComponent(autoTransmisionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(autoAnioEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(autoModeloEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(autoMarcaEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoModeloEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(autoAnioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoChasisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoMotorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(autoKiloEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoCostoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(autoTransmisionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(autoBotonEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jButton6)))
                .addContainerGap())
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton4.setText("Borrar auto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        AutoImgEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.png"))); // NOI18N

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton10.setText("Eliminar auto");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(autoEditBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(AutoImgEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(autoEditBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(AutoImgEdit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Editar", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cliTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Dirección", "Ciudad", "Correo", "Telefono"
            }
        ));
        cliTabla.setEnabled(false);
        cliTabla.setRowHeight(25);
        cliTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cliTabla);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        jLabel16.setText("Filtrar");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/filter.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliTablaMouseClicked
         
    }//GEN-LAST:event_cliTablaMouseClicked

    private void autoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoModeloActionPerformed

    private void autoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoMarcaActionPerformed

    private void autoChasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoChasisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoChasisActionPerformed

    private void autoMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoMotorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(autoPlaca.getText().equals("")||autoModelo.getText().equals("")||autoMarca.getText().equals("")||autoChasis.getText().equals("")||autoMotor.getText().equals("")||autoKilo.getText().equals("")||autoCosto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error: No debe dejar campos vacíos");
        }else{
            if(validarPlaca()==true){
                try {
                    Pg.guardarfoto(autoPlaca.getText(), autoModelo.getText(), autoMarca.getText(), Integer.parseInt(autoAnio.getSelectedItem().toString()),autoChasis.getText(),  autoMotor.getText(),Integer.parseInt(autoKilo.getText()),Double.parseDouble(autoCosto.getText()),autoTransmision.getSelectedItem().toString(), rutaGuardar);
                } catch (IOException ex) {
                    Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
                }
            autoPlaca.setText("");
            autoModelo.setText("");
            autoMarca.setText("");
            autoChasis.setText("");
            autoMotor.setText("");
            autoKilo.setText("");
            autoCosto.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Error: Ingrese una placa valida");
        }
       }
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pg.editarImagen(autoEditBuscar.getText(),autoModeloEdit.getText(),autoMarcaEdit.getText(),Integer.parseInt(autoAnioEdit.getText()),autoChasisEdit.getText(),autoMotorEdit.getText(),Double.parseDouble(autoKiloEdit.getText()),Double.parseDouble(autoCostoEdit.getText()),autoTransmisionEdit.getSelectedItem().toString(),rutaEdit);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            tr.setRowFilter(null);
            cargarTodos();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!autoEditBuscar.getText().equals("")){
             try {
            buscar(autoEditBuscar.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"AVISO: Ingrese una placa");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void autoEditBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoEditBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoEditBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            eliminarAuto(autoEditBuscar.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void autoEditBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoEditBuscarMouseClicked
        autoEditBuscar.setText("");
    }//GEN-LAST:event_autoEditBuscarMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        autoModeloEdit.setText("");
        autoMarcaEdit.setText("");

        autoChasisEdit.setText("");
        autoMotorEdit.setText("");
        autoKiloEdit.setText("");
        autoCostoEdit.setText("");
   
        //Deshabilitar
        autoModeloEdit.setEnabled(false);
        autoMarcaEdit.setEnabled(false);
        autoAnioEdit.setEnabled(false);
        autoChasisEdit.setEnabled(false);
        autoMotorEdit.setEnabled(false);
        autoKiloEdit.setEnabled(false);
        autoCostoEdit.setEnabled(false);
        autoTransmisionEdit.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        
    }//GEN-LAST:event_filterActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String filtro=filter.getText();
        if(!filtro.equals("")){
             
             cliTabla.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(filtro));
        }else{
            tr.setRowFilter(null);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        autoPlaca.setText("");
        autoModelo.setText("");
        autoMarca.setText("");
      
        autoChasis.setText("");
        autoMotor.setText("");
        autoKilo.setText("");
        autoCosto.setText("");
       
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void autoKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoKiloActionPerformed

    private void autoCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoCostoActionPerformed

    private void autoModeloEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoModeloEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoModeloEditActionPerformed

    private void autoMarcaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMarcaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoMarcaEditActionPerformed

    private void autoChasisEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoChasisEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoChasisEditActionPerformed

    private void autoMotorEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMotorEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoMotorEditActionPerformed

    private void autoKiloEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoKiloEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoKiloEditActionPerformed

    private void autoCostoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoCostoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoCostoEditActionPerformed

    private void autoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoPlacaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//            guardarAuto(autoPlaca.getText(), autoModelo.getText(), autoMarca.getText(), Integer.parseInt(autoAnio.getText()),autoChasis.getText(),  autoMotor.getText(),Integer.parseInt(autoKilo.getText()),Double.parseDouble(autoCosto.getText()),autoTransmision.getSelectedItem().toString());            
           
        rutaGuardar = cargarImagen();
        ImageIcon imagen = new ImageIcon(rutaGuardar);   
        //Extrae la clase imagen que corresponde a la posición donde se hizo un clic
            Icon icon = new ImageIcon( imagen.getImage().getScaledInstance( AutoImg.getWidth(),AutoImg.getHeight() , Image.SCALE_DEFAULT) );
        
         this.AutoImg.setIcon( icon  );//coloca imagen en el JLabel
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void autoBotonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoBotonEditActionPerformed
       rutaEdit = editarImagen();
        
    }//GEN-LAST:event_autoBotonEditActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    try {
        eliminarCliente(autoEditBuscar.getText());
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Autos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton10ActionPerformed
   public void eliminarCliente(String placa) throws ClassNotFoundException, SQLException {
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
         String SQL = "DELETE FROM autos WHERE placa = ?";
 
       
        try (Connection con = conn;
                PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setString(1, placa);
            int n = pstmt.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null,"Eliminación exitosa");
            }else{
                JOptionPane.showMessageDialog(null,"Error: Auto inexistente");
            }
            pstmt.close();
            con.close();
            conn.close();
 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Auto desconocido. Contácte con administrador");
      
    
        }
     }
    public boolean validarPlaca(){
     Pattern p = Pattern.compile("^([A-Z]{3}-\\d{3,4})$");
      Matcher m = p.matcher(autoPlaca.getText());
      return m.find();

}
    public String editarImagen(){
         String ruta1="";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
          ruta1 = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
         
        }
        return ruta1;
    }
    public String cargarImagen(){
        String ruta2="";
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
             ruta2 = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            
        }
        return ruta2;
    }
    public void actualizar_lista(){
        Imagen img = Pg.cargarImagen(autoPlaca.getText());
            System.out.println(img);
            //redimensiona imagen
            Icon icon = new ImageIcon( img.getArchivo().getScaledInstance( AutoImg.getWidth(),AutoImg.getHeight() , Image.SCALE_DEFAULT) );
            this.AutoImg.setText("");
            this.AutoImg.setIcon( icon  );//coloca imagen en el JLabel
    }
     private String GenerarCodigo()
    {
        SimpleDateFormat sdf= new SimpleDateFormat("hhmmss");
        return sdf.format(new Date());
    }
    public void guardarAuto(String placa, String modelo, String marca,Integer anio, String chasis, String motor, Integer kilometraje, Double costo,String transmision){

           // Insertar datos a la bd:
            try{
               Class.forName(driver);
               Connection conne=(Connection) DriverManager.getConnection(ruta,user,password);
               Statement consulta=(Statement) conne.createStatement();
               if(existe(placa)){
                    JOptionPane.showMessageDialog(null,"Error: Ya existe un auto con esa placa");
               }else{
                consulta.executeUpdate("insert into autos(modelo, marca, anio,placa, chasis,motor,kilometraje,token,costo,transmision,archivo) values('"+modelo+"', '"+marca+"', "+anio+",'"+placa+"','"+chasis+"','"+motor+"', '"+kilometraje+"',"+0+","+costo+",'"+transmision+"','"+212+"')");

                JOptionPane.showMessageDialog(null,"Auto guardado con éxito");
                autoPlaca.setText("");
                autoModelo.setText("");
                autoMarca.setText("");
               
                autoChasis.setText("");
                autoMotor.setText("");
                autoKilo.setText("");
                autoCosto.setText("");
              
               }
               conne.close();
               consulta.close();
               } catch(SQLException e){
               JOptionPane.showMessageDialog(null,e.getSQLState());

           } catch(ClassNotFoundException e){
               JOptionPane.showMessageDialog(null,"Error inesperado");
       } 
   }
    public void cargarTodos() throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        String Titulo[]={"Placa","Modelo","Marca","Año","Chasis","Motor","Kilometraje","Costo","Transmision"};
        String registros[]=new String[9];
        modelo= new DefaultTableModel(null,Titulo);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM autos");
            while (rs.next())
            {
                registros[0]=rs.getString(5);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                registros[3]=rs.getString(4);
                registros[4]=rs.getString(6);
                registros[5]=rs.getString(7);
                registros[6]=rs.getString(8);
                registros[7]=rs.getString(10);
                registros[8]=rs.getString(11);
                modelo.addRow(registros);
            }
            cliTabla.setModel(modelo);
            rs.close();
            st.close();
            conn.close();
        }
        
    }
    public void buscar(String placa) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String comprobador="";
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM autos WHERE placa='"+placa+"'");
            while (rs.next())
            {
                comprobador=rs.getString(2);
                autoModeloEdit.setText(rs.getString(2));
                autoMarcaEdit.setText(rs.getString(3));
                autoAnioEdit.setText(rs.getString(4));
                autoChasisEdit.setText(rs.getString(6));
                autoMotorEdit.setText(rs.getString(7));
                autoKiloEdit.setText(rs.getString(8));
                autoCostoEdit.setText(rs.getString(10));
                autoTransmisionEdit.setSelectedItem(rs.getString(11));
              
                Imagen img =  Pg.cargarImagen(placa);
                Icon icon = new ImageIcon( img.getArchivo().getScaledInstance( AutoImgEdit.getWidth(),AutoImgEdit.getHeight() , Image.SCALE_DEFAULT) );
                this.AutoImgEdit.setText("");
                this.AutoImgEdit.setIcon( icon  );
                
            }
            cliTabla.setModel(modelo);
            rs.close();
            st.close();
            if(!comprobador.equals("")){
                autoModeloEdit.setEnabled(true);
                autoMarcaEdit.setEnabled(true);
                autoAnioEdit.setEditable(true);
                autoChasisEdit.setEnabled(true);
                autoMotorEdit.setEnabled(true);
                 autoKiloEdit.setEnabled(true);
                autoCostoEdit.setEnabled(true);
                autoTransmisionEdit.setEnabled(true);
                autoBotonEdit.setEnabled(true);
                
            }else{
                JOptionPane.showMessageDialog(null,"Aviso: No se encontró un auto con esa placa");
            }
            conn.clearWarnings();
            conn.close();
            
        }
    }
    public void editar(String modelo, String marca, Integer anio,  String chasis,String motor,Double kilometraje,Double costo,String transmision) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        String SQL = "UPDATE autos "
                + "SET modelo = ? "
                + ", marca = ? "
                + ", anio = ? "
                + ", chasis = ? "
                 + ", motor = ? "
                + ", kilometraje = ? "
                + ", costo = ? "
                + ", transmision = ? "
                + "WHERE  placa= ?";
        try (Connection conn2 = conn;
            PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setString(1, modelo);
            pstmt.setString(2, marca);
            pstmt.setInt(3, anio);
            pstmt.setString(4, chasis);
            pstmt.setString(5, motor);
            pstmt.setDouble(6, kilometraje);
            pstmt.setDouble(7, costo);
            pstmt.setString(8, transmision);
            pstmt.setString(9, autoEditBuscar.getText());
 
            pstmt.executeUpdate();
              pstmt.close();
            conn.close();
            conn2.close();
          
             JOptionPane.showMessageDialog(null, "Actualización exitosa");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
      
    }
     public void eliminarAuto(String placa) throws ClassNotFoundException, SQLException {
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
         String SQL = "DELETE FROM autos WHERE placa = ?";
 
       
        try (Connection con = conn;
                PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setString(1, placa);
            int n = pstmt.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null,"Eliminación exitosa");
            }else{
                JOptionPane.showMessageDialog(null,"Error: Auto inexistente");
            }
            conn.close();
            con.close();
            pstmt.close();
 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Auto inexistente");
      
    
        }
     }
         public boolean existe(String placa) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String comprobador="";
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM autos WHERE placa='"+placa+"'");
            while (rs.next())
            {
                comprobador=rs.getString(2);
            }
            rs.close();
            st.close();
            conn.close();
            if(!comprobador.equals("")){
                return true;
            }else{
                return false;
            }
         
         }
         
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutoImg;
    private javax.swing.JLabel AutoImgEdit;
    private javax.swing.JComboBox<String> autoAnio;
    private javax.swing.JTextField autoAnioEdit;
    private javax.swing.JButton autoBotonEdit;
    private javax.swing.JTextField autoChasis;
    private javax.swing.JTextField autoChasisEdit;
    private javax.swing.JTextField autoCosto;
    private javax.swing.JTextField autoCostoEdit;
    private javax.swing.JTextField autoEditBuscar;
    private javax.swing.JTextField autoKilo;
    private javax.swing.JTextField autoKiloEdit;
    private javax.swing.JTextField autoMarca;
    private javax.swing.JTextField autoMarcaEdit;
    private javax.swing.JTextField autoModelo;
    private javax.swing.JTextField autoModeloEdit;
    private javax.swing.JTextField autoMotor;
    private javax.swing.JTextField autoMotorEdit;
    private javax.swing.JTextField autoPlaca;
    private javax.swing.JComboBox<String> autoTransmision;
    private javax.swing.JComboBox<String> autoTransmisionEdit;
    private javax.swing.JTable cliTabla;
    private javax.swing.JTextField filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
