/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import Main.Main;
import cliente.AddModal;
import cliente.Cliente;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author Jefferson
 */
public class Facturar extends javax.swing.JInternalFrame {
    String driver = "org.postgresql.Driver";
    String ruta = "jdbc:postgresql://localhost:5432/AutoCar";
    String user = "postgres";
    String password = "12345"; 
    String tempoPlaca="";
    public static String tempoCedula="";
    /**
     * Creates new form NewJInternalFrame
     */
    public Facturar() throws ClassNotFoundException, SQLException {
        initComponents();
       cargarFechaActual();
       cargarNumeroFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        factCedu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        faDireccion = new javax.swing.JTextField();
        faNombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        faTelefono = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        faCiudad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        autoCosto = new javax.swing.JTextField();
        autoModelo = new javax.swing.JTextField();
        autoMarca = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        autoPlaca = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        coComprobar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        coAgregar = new javax.swing.JButton();
        coFechaFin = new javax.swing.JTextField();
        coKilo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        coDias = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        numFactura = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        factDescripcion = new javax.swing.JTextArea();
        btnFact = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        fechaActual = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Facturar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Datos generales");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        factCedu.setText("C.I.");
        factCedu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factCeduMouseClicked(evt);
            }
        });
        factCedu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factCeduActionPerformed(evt);
            }
        });
        jPanel1.add(factCedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 44, 28));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 44, 28));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Cliente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel13.setText("Dirección");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));

        faDireccion.setEditable(false);
        jPanel1.add(faDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, -1));

        faNombre.setEditable(false);
        jPanel1.add(faNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 140, -1));

        jLabel17.setText("Teléfono");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        faTelefono.setEditable(false);
        jPanel1.add(faTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, -1));

        jLabel18.setText("Ciudad");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));

        faCiudad.setEditable(false);
        jPanel1.add(faCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 10));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 230, 210));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Autos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel6.setText("Modelo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, -1));

        jLabel7.setText("Marca");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 185, 10));

        jLabel11.setText("Costo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, -1));

        autoCosto.setEditable(false);
        jPanel2.add(autoCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, -1));

        autoModelo.setEditable(false);
        jPanel2.add(autoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        autoMarca.setEditable(false);
        jPanel2.add(autoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        jLabel20.setText("Placa");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        autoPlaca.setEditable(false);
        jPanel2.add(autoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 190, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Contrato");

        coComprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        coComprobar.setText("Comprobar contrato");
        coComprobar.setEnabled(false);
        coComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coComprobarActionPerformed(evt);
            }
        });

        jLabel10.setText("Km:");

        jLabel9.setText("Hasta:");

        coAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        coAgregar.setEnabled(false);
        coAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coAgregarActionPerformed(evt);
            }
        });

        coFechaFin.setEditable(false);

        coKilo.setEditable(false);

        jLabel19.setText("Días");

        coDias.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(coComprobar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coFechaFin))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(coKilo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(22, 22, 22)
                        .addComponent(coDias)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(coFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(coKilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(coDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 210, 210));

        jPanel7.setBackground(new java.awt.Color(50, 93, 127));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("Factura ");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        numFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numFactura.setText("1");
        jPanel6.add(numFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, 20));

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Detalle");

        factDescripcion.setEditable(false);
        factDescripcion.setColumns(20);
        factDescripcion.setRows(5);
        jScrollPane2.setViewportView(factDescripcion);

        btnFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm.png"))); // NOI18N
        btnFact.setToolTipText("");
        btnFact.setEnabled(false);
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setText("Confirmar");

        subtotal.setEditable(false);

        jLabel21.setText("Subtotal");

        jLabel22.setText("IVA");

        iva.setEditable(false);
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });

        jLabel23.setText("Total");

        total.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(41, 41, 41)
                                        .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnFact)
                                .addGap(59, 59, 59))))))
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 650, 170));

        fechaActual.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fechaActual.setForeground(new java.awt.Color(50, 93, 127));
        jPanel6.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 100, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factCeduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factCeduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factCeduActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            buscarCliente(factCedu.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {                                         
            try {
                Main m = new Main();
                
            } catch (SQLException ex) {
                Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
            }
            AddModal w = new AddModal(new Main(),true);
            w.setVisible(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_jButton3ActionPerformed

    private void coComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coComprobarActionPerformed
        try {
            buscarContrato(factCedu.getText());
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_coComprobarActionPerformed

    private void coAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coAgregarActionPerformed
        try {                                         
            try {
                Main m = new Main();
                
            } catch (SQLException ex) {
                Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
            }
            AddContratos w = new AddContratos(new Main(),true);
            w.setVisible(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_coAgregarActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        facturar(factCedu.getText(), tempoPlaca, fechaActual.getText(), factDescripcion.getText());
    }//GEN-LAST:event_btnFactActionPerformed

    private void factCeduMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factCeduMouseClicked
        factCedu.setText("");
    }//GEN-LAST:event_factCeduMouseClicked

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed
    public void total() throws ClassNotFoundException, SQLException{
         
        double costoFinal=Double.parseDouble(autoCosto.getText());
       
        int dias = Integer.parseInt(coDias.getText());
        double subtot =  BigDecimal.valueOf(costoFinal)
                .setScale(3, RoundingMode.HALF_UP)
                 .doubleValue()*dias;
        double iv = subtot*0.12;
        double totF = subtot+iv;
     
       
        subtotal.setText(String.valueOf(subtot));
        iva.setText(String.valueOf(BigDecimal.valueOf(iv)
                .setScale(3, RoundingMode.HALF_UP)
                 .doubleValue()));
        total.setText(String.valueOf(totF));
          
    }
    public void contratoFacturado(String cedula) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        String SQL = "UPDATE contratos "
                + "SET facturado = ? "
                + "WHERE  cedula= ? AND token=0";
        try (Connection conn2 = conn;
            PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setInt(1,1);
            pstmt.setString(2,cedula);
 
            pstmt.executeUpdate();
            pstmt.close();
            conn2.close();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
      
    }
    public void inhabilitarTodo(){
         faNombre.setText("");
                faDireccion.setText("");
                faTelefono.setText("");
                faCiudad.setText("");
                coComprobar.setEnabled(false);
                coAgregar.setEnabled(false);
                factDescripcion.setEditable(false);
                factDescripcion.setText("");
                iva.setText("");
                subtotal.setText("");
                total.setText("");
                btnFact.setEnabled(false);
                coFechaFin.setText("");
                  coKilo.setText("");
                coDias.setText("");
                autoPlaca.setText("");
                autoModelo.setText("");
                autoMarca.setText("");
                autoCosto.setText("");
               
    }
    public void facturar(String cedula, String placa, String fecha,String descripcion){
           // Insertar datos a la bd:
            try{
               Class.forName(driver);
               Connection conne=(Connection) DriverManager.getConnection(ruta,user,password);
               Statement consulta=(Statement) conne.createStatement();
                
                consulta.executeUpdate("insert into facturas(cedula, placa, fecha,descripcion,total) values('"+cedula+"', '"+placa+"', '"+fecha+"','"+descripcion+"',"+Double.parseDouble(total.getText())+")");
                contratoFacturado(cedula);
                JOptionPane.showMessageDialog(null,"Factura guardado con éxito");
                inhabilitarTodo();
            } catch(SQLException e){
               JOptionPane.showMessageDialog(null,e.getMessage());

           } catch(ClassNotFoundException e){
               JOptionPane.showMessageDialog(null,"Error inesperado");
    
   }
    }
    public void buscarCliente(String cedula) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String nombre = "";
         String direccion = "";
          String telefono = "";
           String ciudad = "";
           
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM clientes WHERE cedula='"+cedula+"'");
            while (rs.next())
            {
               nombre = rs.getString(3);
               direccion = rs.getString(4);
               telefono = rs.getString(6);
               ciudad = rs.getString(7);
            }
            if(!nombre.equals("")){
                faNombre.setText(nombre);
                faDireccion.setText(direccion);
                faTelefono.setText(telefono);
                faCiudad.setText(ciudad);
                coComprobar.setEnabled(true);
                coAgregar.setEnabled(true);
                factDescripcion.setEditable(true);
               
                tempoCedula = cedula;
            }else{
                JOptionPane.showMessageDialog(null, "Error: Cliente inexistente");
            }
            rs.close();
            st.close();
            conn.close();
          
         }
         
    }
    public void buscarContrato(String cedula) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String fechaFin = "";
        String kilometros = "";
        String dias = "";
        int facturado=0;
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM contratos WHERE cedula='"+cedula+"' AND token=0");
            while (rs.next())
            { 
                    fechaFin = rs.getString(5);
                    kilometros = rs.getString(8);
                    dias = rs.getString(9);
                    tempoPlaca = rs.getString(3);
                if(Integer.parseInt(rs.getString(10))==1){
                   facturado=1;
                }
               
            }
            
            if(!fechaFin.equals("")){
                if(facturado!=1){
                    Double toBeTruncated = Double.parseDouble(kilometros);
                    Double truncatedDouble = BigDecimal.valueOf(toBeTruncated)
                            .setScale(3, RoundingMode.HALF_UP)
                            .doubleValue();
                    coFechaFin.setText(fechaFin);
                    coKilo.setText(truncatedDouble.toString());
                    coDias.setText(dias);
                    buscarAuto();
                    total();
                    btnFact.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Error: El contrato del cliente ya se encuentra facturado.");
                }
               
                
            }else{
                JOptionPane.showMessageDialog(null, "Error: El cliente no posee contratos activos");
            }
            rs.close();
            st.close();
            conn.close();
          
         }
         
    }
     public void buscarAuto() throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String modelo = "";
         String marca = "";
          String costo = "";
          
           
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM autos WHERE placa='"+tempoPlaca+"'");
            while (rs.next())
            {
               modelo = rs.getString(2);
               marca = rs.getString(3);
               costo = rs.getString(10);
              
            }
            if(!modelo.equals("")){
                autoPlaca.setText(tempoPlaca);
                autoModelo.setText(modelo);
                autoMarca.setText(marca);
                autoCosto.setText(String.valueOf(BigDecimal.valueOf(Double.parseDouble(costo))
                            .setScale(3, RoundingMode.HALF_UP)
                            .doubleValue()));
               
            }
            rs.close();
            st.close();
            conn.close();
          
         }
         
    }
     
public void cargarFechaActual(){
    Calendar c = new GregorianCalendar();
    String dia = Integer.toString(c.get(Calendar.DATE));
    String mes = Integer.toString(c.get(Calendar.MONTH));
    String annio = Integer.toString(c.get(Calendar.YEAR));
    fechaActual.setText(annio+"/"+mes+"/"+dia);
    
   
}
public void cargarNumeroFactura()throws ClassNotFoundException, SQLException{
    Class.forName(driver);
        int i=0;
       
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM facturas");
            while (rs.next())
            {
               i = Integer.parseInt(rs.getString(1));
            }
            numFactura.setText(String.valueOf(i+1));
            rs.close();
            st.close();
            conn.close();
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autoCosto;
    private javax.swing.JTextField autoMarca;
    private javax.swing.JTextField autoModelo;
    private javax.swing.JTextField autoPlaca;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton coAgregar;
    private javax.swing.JButton coComprobar;
    private javax.swing.JTextField coDias;
    private javax.swing.JTextField coFechaFin;
    private javax.swing.JTextField coKilo;
    private javax.swing.JTextField faCiudad;
    private javax.swing.JTextField faDireccion;
    private javax.swing.JTextField faNombre;
    private javax.swing.JTextField faTelefono;
    private javax.swing.JTextField factCedu;
    private javax.swing.JTextArea factDescripcion;
    private javax.swing.JLabel fechaActual;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel numFactura;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
