/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solicitudes;

 

import usuarios.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jefferson
 */
public class Solicitudes extends javax.swing.JInternalFrame {

    String driver = "org.postgresql.Driver";
    String ruta = "jdbc:postgresql://localhost:5432/AutoCar";
    String user = "postgres";
    String password = "12345"; 
    DefaultTableModel modelo;
  
    /**
     * Creates new form Cliente
     */
    public Solicitudes() throws ClassNotFoundException, SQLException {
        initComponents();
        cargarTodos();
        tr=new TableRowSorter<>(modelo);
    }

    TableRowSorter<TableModel> tr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soliCedula = new javax.swing.JTextField();
        soliNombre = new javax.swing.JTextField();
        soliDireccion = new javax.swing.JTextField();
        soliCiudad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        soliPlaca = new javax.swing.JTextField();
        soliFecha = new javax.swing.JTextField();
        soliCorreo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        soliBuscarEdit = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        soliNombreEdit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        soliDireccionEdit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        soliCorreoEdit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        soliCiudadEdit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        soliPlacaEdit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        soliFechaEdit = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cliTabla = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        filter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(50, 93, 127));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Agregar solicitud");

        soliCedula.setName(""); // NOI18N
        soliCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliCedulaActionPerformed(evt);
            }
        });

        soliNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliNombreActionPerformed(evt);
            }
        });

        soliDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliDireccionActionPerformed(evt);
            }
        });

        soliCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliCiudadActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Agregar");

        jLabel3.setText("Cédula");

        jLabel6.setText("Nombre");

        jLabel7.setText("Dirección");

        jLabel8.setText("Correo");

        jLabel9.setText("Ciudad");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deny.png"))); // NOI18N
        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha");

        jLabel18.setText("Placa");

        soliPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliPlacaActionPerformed(evt);
            }
        });

        soliFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliFechaActionPerformed(evt);
            }
        });

        soliCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 135, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(soliNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(soliDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soliCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soliCedula)
                                    .addComponent(soliPlaca)
                                    .addComponent(soliFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soliCorreo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soliCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soliDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(soliCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soliCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soliPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(soliFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton8))
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/solicitud.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel17))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        soliBuscarEdit.setText("Cédula");
        soliBuscarEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soliBuscarEditMouseClicked(evt);
            }
        });
        soliBuscarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliBuscarEditActionPerformed(evt);
            }
        });
        jPanel6.add(soliBuscarEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 124, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 12, 45, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Editar solicitud");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 43, -1));

        jLabel5.setText("Editar");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deny.png"))); // NOI18N
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel12.setText("Nombre");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, -1, -1));

        soliNombreEdit.setEnabled(false);
        soliNombreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliNombreEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliNombreEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 286, -1));

        jLabel13.setText("Dirección");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 95, -1, -1));

        soliDireccionEdit.setEnabled(false);
        soliDireccionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliDireccionEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliDireccionEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 286, -1));

        jLabel14.setText("Correo");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        soliCorreoEdit.setEnabled(false);
        soliCorreoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliCorreoEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliCorreoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 286, -1));

        jLabel15.setText("Ciudad");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));

        soliCiudadEdit.setEnabled(false);
        soliCiudadEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliCiudadEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliCiudadEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 286, -1));

        jLabel19.setText("Placa");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        soliPlacaEdit.setEnabled(false);
        soliPlacaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliPlacaEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliPlacaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 286, -1));

        jLabel20.setText("Fecha");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        soliFechaEdit.setEnabled(false);
        soliFechaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soliFechaEditActionPerformed(evt);
            }
        });
        jPanel3.add(soliFechaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 286, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 53, 480, 330));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton4.setText("Borrar solicitud");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 12, -1, 20));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm.png"))); // NOI18N
        jButton10.setText("VALIDAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 35));

        jTabbedPane1.addTab("Editar", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cliTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Dirección", "Ciudad", "Correo", "Telefono"
            }
        ));
        cliTabla.setEnabled(false);
        cliTabla.setRowHeight(25);
        cliTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cliTabla);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        jLabel16.setText("Filtrar");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/filter.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliTablaMouseClicked
         
    }//GEN-LAST:event_cliTablaMouseClicked

    private void soliNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliNombreActionPerformed

    private void soliDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliDireccionActionPerformed

    private void soliCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliCiudadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        guardarSolicitud(soliCedula.getText(), soliNombre.getText(), soliDireccion.getText(), soliCorreo.getText(),soliCiudad.getText(), soliPlaca.getText(),soliFecha.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            editar(soliNombreEdit.getText(), soliDireccionEdit.getText(), soliCorreoEdit.getText(),soliCiudadEdit.getText(), soliPlacaEdit.getText(),soliFechaEdit.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            tr.setRowFilter(null);
            cargarTodos();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!soliBuscarEdit.getText().equals("")){
             try {
            buscar(soliBuscarEdit.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"AVISO: Ingrese una cédula");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void soliBuscarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliBuscarEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliBuscarEditActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            eliminarSolicitud(soliBuscarEdit.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void soliBuscarEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soliBuscarEditMouseClicked
        soliBuscarEdit.setText("");
    }//GEN-LAST:event_soliBuscarEditMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        soliNombreEdit.setText("");
        soliDireccionEdit.setText("");
        soliCorreoEdit.setText("");
        soliPlacaEdit.setText("");
        soliCiudadEdit.setText("");
        soliFechaEdit.setText("");
        //Deshabilitar
        soliNombreEdit.setEnabled(false);
        soliDireccionEdit.setEnabled(false);
        soliCorreoEdit.setEnabled(false);
        soliPlacaEdit.setEnabled(false);
        soliCiudadEdit.setEnabled(false);
        soliFechaEdit.setEnabled(false);
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        
    }//GEN-LAST:event_filterActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String filtro=filter.getText();
        if(!filtro.equals("")){
             
             cliTabla.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(filtro));
        }else{
            tr.setRowFilter(null);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        soliCedula.setText("");
        soliNombre.setText("");
        soliDireccion.setText("");
        soliCorreo.setText("");
        soliCiudad.setText("");
        soliPlaca.setText("");
      
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void soliCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliCedulaActionPerformed

    private void soliPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliPlacaActionPerformed

    private void soliFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliFechaActionPerformed

    private void soliCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliCorreoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            validar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void soliNombreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliNombreEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliNombreEditActionPerformed

    private void soliDireccionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliDireccionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliDireccionEditActionPerformed

    private void soliCorreoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliCorreoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliCorreoEditActionPerformed

    private void soliCiudadEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliCiudadEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliCiudadEditActionPerformed

    private void soliPlacaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliPlacaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliPlacaEditActionPerformed

    private void soliFechaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soliFechaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soliFechaEditActionPerformed
    public void validar() throws ClassNotFoundException, SQLException{
        if(!soliBuscarEdit.getText().equals("")&&!soliBuscarEdit.getText().equals("Cédula")){
            if(comprobarValidacion(soliBuscarEdit.getText())==false){
                Class.forName(driver);
                Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
                String SQL = "UPDATE solicitudes "
                        + "SET token = ? "
                        + "WHERE  cedula= ?";
                try (Connection conn2 = conn;
                    PreparedStatement pstmt = conn.prepareStatement(SQL)) {
                    pstmt.setInt(1, 1);
                    
                    pstmt.setString(2, soliBuscarEdit.getText());

                    pstmt.executeUpdate();
                      pstmt.close();
                    conn.close();
                    conn2.close();

                     JOptionPane.showMessageDialog(null, "Validación exitosa");
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }   
            }else{
                JOptionPane.showMessageDialog(null, "Aviso: La solicitud ya está validad o no existe");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Aviso: Ingrese una cédula");
        }
      
    }
    public boolean comprobarValidacion(String cedula) throws ClassNotFoundException, SQLException{
     
        Class.forName(driver);
         
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
       
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM solicitudes WHERE cedula='"+cedula+"'");
            while (rs.next())
            {
                
                if(Integer.parseInt(rs.getString(9))==0){
                  
                    return false;
                }else if(Integer.parseInt(rs.getString(9))==1){
                    
                    
                    return true;
                }
               
            }
           
            rs.close();
            st.close();
            conn.close();
        }
        return false;
    }
    public void guardarSolicitud(String cedula, String nombre, String direccion,String correo,  String ciudad, String placa, String fecha){
           // Insertar datos a la bd:
            try{
               Class.forName(driver);
               Connection conne=(Connection) DriverManager.getConnection(ruta,user,password);
               Statement consulta=(Statement) conne.createStatement();
               if(existe(cedula)){
                    JOptionPane.showMessageDialog(null,"Error: Ya existe una solicitud con esa cédula");
               }else{
                
                consulta.executeUpdate("insert into solicitudes(cedula, nombre, direccion,correo, ciudad,placa,fecha,token) values('"+cedula+"', '"+nombre+"', '"+direccion+"','"+correo+"','"+ciudad+"','"+placa+"', '"+fecha+"',"+0+")");

                JOptionPane.showMessageDialog(null,"Solicitud guardada con éxito");
                soliCedula.setText("");
                soliNombre.setText("");
                soliDireccion.setText("");
                soliCorreo.setText("");
                soliCiudad.setText("");
                soliPlaca.setText("");
                soliFecha.setText("");
                
               }
               conne.close();
               consulta.close();
               
               } catch(SQLException e){
               JOptionPane.showMessageDialog(null,e.getErrorCode());

           } catch(ClassNotFoundException e){
               JOptionPane.showMessageDialog(null,"Error inesperado");
       } 
   }
    public void cargarTodos() throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        String Titulo[]={"Cédula","Nombre","Direccion","Correo","Ciudad","Placa","Fecha","Validado"};
        String registros[]=new String[8];
        modelo= new DefaultTableModel(null,Titulo);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM solicitudes");
            while (rs.next())
            {
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                registros[3]=rs.getString(4);
                registros[4]=rs.getString(5);
                registros[5]=rs.getString(6);
                registros[6]=rs.getString(7);
                if(Integer.parseInt(rs.getString(9))==0){
                   registros[7]="No";
                }else if(Integer.parseInt(rs.getString(9))==1){
                   registros[7]="Sí";
                }
               
                modelo.addRow(registros);
            }
            cliTabla.setModel(modelo);
            rs.close();
            st.close();
            conn.close();
        }
        
    }
    public void buscar(String cedula) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        String comprobador="";
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT * FROM solicitudes WHERE cedula='"+cedula+"'");
            while (rs.next())
            {
                comprobador=rs.getString(2);
                soliNombreEdit.setText(rs.getString(2));
                soliDireccionEdit.setText(rs.getString(3));
                soliCorreoEdit.setText(rs.getString(4));
                soliCiudadEdit.setText(rs.getString(5));
                soliPlacaEdit.setText(rs.getString(6));
                soliFechaEdit.setText(rs.getString(7));
                
            }
            cliTabla.setModel(modelo);
            rs.close();
            st.close();
            if(!comprobador.equals("")){
                soliNombreEdit.setEnabled(true);
                soliDireccionEdit.setEnabled(true);
                soliCorreoEdit.setEnabled(true);
                soliCiudadEdit.setEnabled(true);
                soliPlacaEdit.setEnabled(true);
                soliFechaEdit.setEnabled(true);
               
            }else{
                JOptionPane.showMessageDialog(null,"Aviso: No se encontró una solicitud con esa cédula");
            }
            conn.clearWarnings();
            conn.close();
            
        }
    }

    public void editar(String nombre, String direccion, String correo,  String ciudad,String placa,String fecha) throws ClassNotFoundException, SQLException{
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
        String SQL = "UPDATE solicitudes "
                + "SET nombre = ? "
                + ", direccion = ? "
                + ", correo = ? "
                + ", ciudad = ? "
                 + ", placa = ? "
                + ", fecha = ? "
                + "WHERE  cedula= ?";
        try (Connection conn2 = conn;
            PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setString(1, nombre);
            pstmt.setString(2, direccion);
            pstmt.setString(3, correo);
            pstmt.setString(4, ciudad);
            pstmt.setString(5, placa);
            pstmt.setString(6, fecha);
           
            pstmt.setString(7, soliBuscarEdit.getText());
 
            pstmt.executeUpdate();
              pstmt.close();
            conn.close();
            conn2.close();
          
             JOptionPane.showMessageDialog(null, "Actualización exitosa");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
      
    }
     public void eliminarSolicitud(String cedula) throws ClassNotFoundException, SQLException {
        Class.forName(driver);
        Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
         String SQL = "DELETE FROM solicitudes WHERE cedula = ?";
        try (Connection con = conn;
                PreparedStatement pstmt = conn.prepareStatement(SQL)) {
 
            pstmt.setString(1, cedula);
            int n = pstmt.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null,"Eliminación exitosa");
            }else{
                JOptionPane.showMessageDialog(null,"Error: Solicitud inexistente");
            }
            conn.close();
            con.close();
            pstmt.close();
 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Solicitud inexistente");
      
    
        }
     }
         public boolean existe(String cedula) throws ClassNotFoundException, SQLException{
            Class.forName(driver);
            String comprobador="";
            Connection conn=(Connection) DriverManager.getConnection(ruta,user,password);
            try (Statement st = conn.createStatement()) {
                ResultSet rs = st.executeQuery("SELECT * FROM solicitudes WHERE cedula='"+cedula+"'");
                while (rs.next())
                {
                    comprobador=rs.getString(2);
                }
                rs.close();
                st.close();
                conn.close();
                if(!comprobador.equals("")){
                    return true;
                }else{
                    return false;
                }

         }
         
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cliTabla;
    private javax.swing.JTextField filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField soliBuscarEdit;
    private javax.swing.JTextField soliCedula;
    private javax.swing.JTextField soliCiudad;
    private javax.swing.JTextField soliCiudadEdit;
    private javax.swing.JTextField soliCorreo;
    private javax.swing.JTextField soliCorreoEdit;
    private javax.swing.JTextField soliDireccion;
    private javax.swing.JTextField soliDireccionEdit;
    private javax.swing.JTextField soliFecha;
    private javax.swing.JTextField soliFechaEdit;
    private javax.swing.JTextField soliNombre;
    private javax.swing.JTextField soliNombreEdit;
    private javax.swing.JTextField soliPlaca;
    private javax.swing.JTextField soliPlacaEdit;
    // End of variables declaration//GEN-END:variables
}
